version: '2.2'
services:

# modified version of docker-compose.localhost.yml
# for thuenen specific stack and config
# HOST IP SET TO localhost

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
      - logs_django:/var/log
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost/
      - ALLOWED_HOSTS=['localhost', '*',]
      - GEOSERVER_PUBLIC_LOCATION=http://localhost/gs/

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost/
      - ALLOWED_HOSTS=['localhost', '*',]
      - GEOSERVER_PUBLIC_LOCATION=http://localhost/gs/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=

  geonode:
    volumes:
      - logs_nginx:/var/log/nginx

# forward PostgreSQL port to host
  db:
    image:  geonode/postgis:10
    ports:
      - "5432:5432"


volumes:
  statics:
    name: ${COMPOSE_PROJECT_NAME}-statics
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/statics
  geoserver-data-dir:
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/geoserver
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/dbdata
  dbbackups:
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/dbbackups
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq
  logs_nginx:
    name: ${COMPOSE_PROJECT_NAME}-logs_nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/logs/nginx
  logs_django:
    name: ${COMPOSE_PROJECT_NAME}-logs_django
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/data/logs/django