version: '2.2'
services:

# HOST IP SET TO 134.110.18.170 (k8sSlave01)

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
      - logs_django:/var/log
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=134.110.18.170
      - GEONODE_LB_PORT=80
      - SITEURL=http://134.110.18.170/
      - ALLOWED_HOSTS=['134.110.18.170', '*',]
      - GEOSERVER_PUBLIC_LOCATION=http://134.110.18.170/gs/
    env_file:
      - ./scripts/docker/env/production/django_k8sSlave01.env

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=134.110.18.170
      - GEONODE_LB_PORT=80
      - SITEURL=http://134.110.18.170/
      - ALLOWED_HOSTS=['134.110.18.170', '*',]
      - GEOSERVER_PUBLIC_LOCATION=http://134.110.18.170/gs/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=134.110.18.170
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=

  geonode:
    volumes:
      - logs_nginx:/var/log/nginx
      
# forward PostgreSQL port to host
  db:
    image:  geonode/postgis:10
    ports:
      - "5432:5432"


volumes:
  statics:
    name: ${COMPOSE_PROJECT_NAME}-statics
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/statics # does not work 
      device: /home/administrator/data/statics
  geoserver-data-dir:
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/geoserver
      device: /home/administrator/data/geoserver
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/dbdata
      device: /home/administrator/data/dbdata
  dbbackups:
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/dbbackups
      device: /home/administrator/data/dbbackups
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq
  logs_nginx:
    name: ${COMPOSE_PROJECT_NAME}-logs_nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/logs/nginx
      device: /home/administrator/data/logs/nginx
  logs_django:
    name: ${COMPOSE_PROJECT_NAME}-logs_django
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: ../data/logs/django
      device: /home/administrator/data/logs/django